import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BarraLateral from "@/components/BarraLateral";
import BarraDePesquisa from "@/components/BarraDePesquisa";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`flex h-screen`}
      >
        <BarraLateral />
        <div className="flex bg-violet-500 h-16 w-full items-center">
          <BarraDePesquisa />
        </div>
        {children}
      </body>
    </html>
  );
}
